#!/bin/sh

TYPE=`jq -r .data[0].type $1`

if [ $TYPE != GroupMessage ]
then
    exit
fi

GRPNO=`jq -r .data[0].sender.group.id $1`
MSG=`~/shbot/getmsg < $1` # e.g. {type: ..., text: ...}
MTYPE=`echo $MSG | jq -r .type`

if [ $MTYPE == Image ]
then
    IID=`echo $MSG | jq -r .imageId`
    C=~/cache/handler.cache
    ~/bin/imghandler $IID > $C && ~/shbot/send $GRPNO "`cat $C`"
fi

MN=`jq -r .data[0].sender.memberName $1`
SENDER_ID=`jq -r .data[0].sender.id $1`
TXT=`echo $MSG | jq -r .text`
ISADMIN=$([ `cat ~/adminid` -eq $SENDER_ID ] && echo "y")

~/workernana $GRPNO "$TXT" "$ISADMIN" || python3 ~/handler.py $GRPNO "$TXT" "$MN"
