#!/bin/sh

# nc -l 12321

MAH='curl localhost:8080'

MSGCNT=`$MAH/countMessage 2>/dev/null | jq '.data'`
echo $MSGCNT

if [ $MSGCNT != 0 ]
then
    MSG=`$MAH/'fetchMessage?count=1' 2>/dev/null`

    if echo $MSG | grep '\"data\":\[\]' > /dev/null
    then
        exit
    fi

    LOG=~/log/`~/ts`.json
    echo $MSG | json_pp -json_opt utf8,pretty > $LOG
    ~/shbot/handler $LOG
fi
