#!/bin/sh

# nc -l 12321

MAH='curl localhost:8080'

MSGCNT=`$MAH/countMessage | jq '.data'`

if [ $MSGCNT != 0 ]
then
    MSG=`$MAH/'fetchMessage?count=1'`
    LOG=~/log/`~/ts`.json
    echo $MSG | json_pp > $LOG
    python3 ~/handler.py < $LOG
fi
