#!/bin/sh

MAH='curl localhost:8080'
GRPNO=$1
TEXT=`echo "$2" | head -c 400` # shorter
DELAY=~/cache/lastsend
D={\"target\":$GRPNO,\"messageChain\":\[{\"type\":\"Plain\",\"text\":\"$TEXT\"}\]}

sec ()
{
    date +%S
}

((NEXT=`cat $DELAY`+5))

if [ $NEXT -gt 59 ]
then
    NEXT=1
fi

while true
do
    echo Now `sec`, $NEXT
    if [ `sec` -gt $NEXT ]
    then
        sec > $DELAY
        break
    else
        echo sleeping to $NEXT "(`sec`)"
        sleep 2
    fi
done

echo `$MAH/sendGroupMessage -d "$D"`
